# Generated by Django 3.2.23 on 2023-12-21 01:03

from django.db import migrations

def populate_data(apps, schema_editor):
    BookStatus = apps.get_model('libraries', 'BookStatus')
    BookStatus.objects.create(name='Available')
    BookStatus.objects.create(name='On Hold')
    BookStatus.objects.create(name='In Transit')
    BookStatus.objects.create(name='Checked Out')
    BookStatus.objects.create(name='Renewed')
    BookStatus.objects.create(name='Missing')
    BookStatus.objects.create(name='Lost')
    BookStatus.objects.create(name='Damaged')
    BookStatus.objects.create(name='Being Repaired')
    BookStatus.objects.create(name='Reference Only')
    BookStatus.objects.create(name='Reserved')



class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(populate_data)
    ]
