# Generated by Django 3.2.23 on 2023-12-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0003_auto_20231220_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='rnc',
            field=models.CharField(default='000-0000000-0', max_length=13, unique=True),
        ),
    ]
