# Generated by Django 3.2.23 on 2024-01-02 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0006_rent_count_to_rent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='count_to_rent',
            new_name='amount_to_rent',
        ),
    ]
