# Generated by Django 3.2.23 on 2024-01-11 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0008_bookgenders'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='libraries.bookgenders'),
            preserve_default=False,
        ),
    ]
