# Generated by Django 3.2.23 on 2024-01-16 23:30

from django.db import migrations, models

def populate_data(apps, schema_editor):
    RentStatus = apps.get_model('libraries', 'RentStatus')
    RentStatus.objects.create(name='Checked Out')
    RentStatus.objects.create(name='Overdue')
    RentStatus.objects.create(name='Renewed')
    RentStatus.objects.create(name='On Hold/Reserved')
    RentStatus.objects.create(name='Returned')
    RentStatus.objects.create(name='Lost or Damaged')
    RentStatus.objects.create(name='In Transit')

class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0009_book_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RunPython(populate_data)
    ]
