# Generated by Django 3.2.23 on 2024-01-17 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0010_rentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='libraries.rentstatus'),
            preserve_default=False,
        ),
    ]
