# Generated by Django 3.2.23 on 2024-01-17 00:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0011_rent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='created_date',
            field=models.DateField(default=datetime.date(2024, 1, 16)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rent',
            name='modified_date',
            field=models.DateField(default=datetime.date(2024, 1, 16)),
            preserve_default=False,
        ),
    ]
