# Generated by Django 3.2.23 on 2023-12-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='rnc',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
