# Generated by Django 3.2.23 on 2023-12-21 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
        ('persons', '0003_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=150)),
                ('rnc', models.CharField(max_length=13, unique=True)),
                ('birthday', models.DateField()),
                ('alias', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=150)),
                ('rnc', models.CharField(max_length=13, unique=True)),
                ('birthday', models.DateField()),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='libraries.library')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=150)),
                ('rnc', models.CharField(max_length=13, unique=True)),
                ('birthday', models.DateField()),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='libraries.library')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
