# Generated by Django 3.2.23 on 2024-01-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0006_auto_20240116_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_time',
            field=models.IntegerField(default=7),
        ),
    ]
